version: '3.4'

services:
  mamrenewer:
    image: ${DOCKER_REGISTRY-}mamrenewer
    build:
      context: .
      dockerfile: MamRenewer/Dockerfile
      
  #for ui testing. see also https://github.com/SeleniumHQ/docker-selenium#debugging
  selenium-firefox-standalone:
    image: selenium/standalone-firefox:4.0.0-beta-1-prerelease-20201208
    shm_size: '2gb'
    ports:
      - 4444:4444
      - 5900:5900
