version: '3.4'

services:
  mamrenewer:
    image: ${DOCKER_REGISTRY-}mamrenewer
    build:
      context: .
      dockerfile: MamRenewer/Dockerfile
    volumes:
      - ./compose/data:/data
    environment:
      - MAMBOT__SELENIUMHUBADDRESS=http://selenium-firefox-standalone:4444/wd/hub

      
  #for ui testing. see also https://github.com/SeleniumHQ/docker-selenium#debugging
  selenium-firefox-standalone:
    image: selenium/standalone-firefox:4
    shm_size: '2gb'
    ports:
      - 4444:4444
      - 5900:5900
